/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        ALayout: typeof import('@arco-design/web-vue')['Layout']
        ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
        ALayoutFooter: typeof import('@arco-design/web-vue')['LayoutFooter']
        ALayoutHeader: typeof import('@arco-design/web-vue')['LayoutHeader']
        ALayoutSider: typeof import('@arco-design/web-vue')['LayoutSider']
        HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
        IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
        IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
        IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
        IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
        IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
        RouterLink: typeof import('vue-router')['RouterLink']
        RouterView: typeof import('vue-router')['RouterView']
        TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
        WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
    }
}
